# AWS EC2 인스턴스를 생성하는 템플릿
# parameter, output 정의
# 저장공간, 보안그룹 지정, nginx 자동 설치
AWSTemplateFormatVersion: "2010-09-09"
Description: Hello, CloudFormation

Parameters:
  KeyName:
    Type: String
    Default: cloud2024
    Description: Please insert instance's Private Key Name
  TagName:
    Type: String
    Description: Please insert Tag Name Value


Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-01ed8ade75d4eee2f
      InstanceType: t2.micro
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeSize: 20
            VolumeType: gp2
      KeyName: !Ref KeyName
      Tags:
        - Key: Name
          Value : !Ref TagName
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo apt update
          sudo apt install -y nginx
      SecurityGroups:
        - Ref: MySecurityGroup

  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH, HTTP access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

      Tags:
        - Key: Name
          Value: CF01c-SG




Outputs:
  InstanceIP:
    Value: !GetAtt MyInstance.PublicIp
    Description: print created instance's public IP address